services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_pgvector
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_setup:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
